In [4]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [6]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


there is difference in datatype of both variables list_ is list and array_list is array.

#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [14]:
def datatypes(lst):
  for i in lst:
    print(type(i))

In [15]:
datatypes(list_)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
datatypes(array_list)

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [19]:
converted_list = [int(i) for i in list_]
print(datatypes(converted_list))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
None


In [20]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [26]:
print(np.shape(num_array))
print(np.size(num_array))

(2, 3)
6


#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [29]:
zeros_matrix = np.zeros((3,3))
zeros_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
